# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN pip install --upgrade pip

# Upgrade pip to avoid any outdated pip issues and install TensorFlow separately
RUN pip install --upgrade pip && \
    pip install --no-cache-dir tensorflow && \
    pip install --no-cache-dir fastapi uvicorn pydantic numpy

# Expose the port the app runs on
EXPOSE 8000

# Run the FastAPI server using Uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
